remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: WaveUSB Project Homepage
description: The WaveUSB Project programmed in shell(or batch for Windows) and java. A user friendly alternative to Rufus
lsi: false
safe: true
source: RishonDev/waveusb.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

show_downloads: true
